### ISSUE TITLE
VideoCapture error on Anaconda

### ISSUE THREAD

**Issue by staticdev** [scikit-video/scikit-video#18] opened 2016-12-14 17:03 UTC
I am using Python 3.5.2, Anaconda 4.2.0 (64-bit), OpenCV 3.1.0 installed with conda install -c menpo opencv3=3.1.0. I installed
sudo apt-get install libav-tools
pip install scikit-video

Then:
python
import skvideo.io
cap = VideoCapture('2538-5_70133.avi')

Error:
cap = VideoCapture('2538-5_70133.avi')
Traceback (most recent call last):
File "", line 1, in
File "/home/01677387637/anaconda3/lib/python3.5/site-packages/skvideo/io/init.py", line 26, in init
self.info = self.get_info()
File "/home/01677387637/anaconda3/lib/python3.5/site-packages/skvideo/io/init.py", line 119, in get_info
info = json.loads(output)
File "/home/01677387637/anaconda3/lib/python3.5/json/init.py", line 312, in loads
s.class.name))
TypeError: the JSON object must be str, not 'bytes'

**Comment by beyondmetis** [comment] 2016-12-14 18:04
I know exactly what the problem is. Read "I installed scikit-video, but the API I installed does not match the website! How do I fix this?" on the FAQ here: http://www.scikit-video.org/stable/faq.html

After doing this, you will no longer have access to the VideoCapture API, since @aizvorski has not merged the old code-base yet. Good news is that you can checkout the current API on the scikit-video website.

**Comment by staticdev** [comment] 2016-12-14 18:14
Also the FAQ should be updated.. this print command is deprecated, it needs parenthesis to work with Python 2 and 3. And it is not useful when you have Anaconda, because it doesn't show the version:
/home/01677387637/anaconda3/lib/python3.5/site-packages/skvideo/__init__.py

**Comment by beyondmetis** [comment] 2016-12-14 18:24
Did you do this:
```
$ sudo pip uninstall scikit-video
$ sudo pip install sk-video
```
If you did, then the uninstall isn't working since the file "site-packages/skvideo/init.py" does not exist in the current scikit-video. As for the MKL errors, I'm not convinced they are related to scikit-video.

We do need to make the FAQ more python agnostic.

**Comment by staticdev** [comment] 2016-12-14 20:29
Yes, I did the pip uninstall and install. Maybe scikit-video is already coming bundled with Anaconda. I will investigate.

**Comment by staticdev** [comment] 2016-12-15 11:02
Besides the detail of the 
/home/01677387637/anaconda3/lib/python3.5/site-packages/skvideo/init.py when I do print(skvideo.__file__). But now VideoCapture doesn't exist anymore:
>>> import skvideo.io
>>> cap = skvideo.io.VideoCapture(sys.argv[1])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'skvideo.io' has no attribute 'VideoCapture'

**Comment by beyondmetis** [comment] 2016-12-31 19:19
VideoCapture isn't actually part of scikit-video, thus you are seeing correct behavior with your Python 3 install.

**Closed** 2017-03-05 22:31 UTC
