### ISSUE TITLE
Broken pipe error with skvideo.io.vwrite

### ISSUE THREAD

**Issue by joemathai** [scikit-video/scikit-video#32] opened 2017-04-21 23:39 UTC
Hi, 
I am getting a broken pipe error with a list of numpy frames. The shape is (no_frames, h, w, 3). Is there anything I am doing wrong ?

skvideo.io.vwrite("outputvideo.mp4", frames, backend="libav")

 File "/home/jj/miniconda3/lib/python3.6/site-packages/skvideo/io/io.py", line 71, in vwrite
    writer.writeFrame(videodata[t])
  File "/home/jj/miniconda3/lib/python3.6/site-packages/skvideo/io/avconv.py", line 456, in writeFrame
    raise IOError(msg)
OSError: [Errno 32] Broken pipe

avconv COMMAND:
/usr/bin/avconv -y -f rawvideo -pix_fmt rgb24 -s 126x126 -i pipe: -sws_flags bitexact outputvideo.mp4

avconv STDERR OUTPUT:

**Comment by beyondmetis** [comment] 2017-04-22 01:07
I was unable to reproduce this problem with both python2.7 and python3.5. Here is what I ran:

> import skvideo.io
> import numpy as np
> 
> ar = np.zeros((10, 126, 126, 3))
> 
> skvideo.io.vwrite("test.mp4", ar, backend='libav')

I used libav version "v12_dev0-2305-g77a44f5" that I happened to have installed on my system. What version are you using?

**Comment by joemathai** [comment] 2017-04-22 21:31
Using a random input seems to work fine for me as well.

**Comment by beyondmetis** [comment] 2017-04-22 23:47
Did you find out what the problem was?

**Comment by joemathai** [comment] 2017-04-24 20:15
@beyondmetis I am not sure what the error was but changing the backend to FFmpeg seems to fix it.

**Comment by beyondmetis** [comment] 2017-05-24 21:19
Closing until further information is provided

**Closed by beyondmetis** 2017-05-24 21:19 UTC
